T = readtable('/Users/zsayali1/Documents/2104_Creativity/AUTRAT.csv');

Baseline=T(strcmp(T.Dose,'Baseline'),:)
Placebo=T(strcmp(T.Dose,'Placebo'),:)
Psilo=T(strcmp(T.Dose,'10mg/70kg'),:)

% Join tables on ParticipantID and Session, keeping only matching rows
matchedTable = innerjoin(Baseline, Placebo, 'Keys', 'ParticipantID', ...
                         'RightVariables', {'ParticipantID','Dose', 'Session', 'RAT_Accuracy', 'RAT_Accurate_Insight', ...
                                            'RAT_Inaccurate_Insight', 'RAT_N_A_Insight', ...
                                            'AUT_Originality', 'AUT_Fluency'}, ...
                         'LeftVariables', {'ParticipantID','Dose', 'Session','RAT_Accuracy', 'RAT_Accurate_Insight', ...
                                            'RAT_Inaccurate_Insight', 'RAT_N_A_Insight', ...
                                            'AUT_Originality', 'AUT_Fluency'});

resultsPlacebo = table(matchedTable.ParticipantID_Baseline, ...
    Placebo.Dose, Placebo.Session,...
    Placebo.RAT_Accuracy - matchedTable.RAT_Accuracy_Baseline, ...
    Placebo.RAT_Accurate_Insight - matchedTable.RAT_Accurate_Insight_Baseline, ...
    Placebo.RAT_Inaccurate_Insight - matchedTable.RAT_Inaccurate_Insight_Baseline, ...
    Placebo.RAT_N_A_Insight - matchedTable.RAT_N_A_Insight_Baseline, ...
    Placebo.AUT_Originality - matchedTable.AUT_Originality_Baseline, ...
    Placebo.AUT_Fluency - matchedTable.AUT_Fluency_Baseline, ...
    'VariableNames', {'ParticipantID', 'Dose', 'Session', 'RAT_Accuracy_Diff', 'RAT_Accurate_Insight_Diff', ...
                      'RAT_Inaccurate_Insight_Diff', 'RAT_N_A_Insight_Diff', ...
                      'AUT_Originality_Diff', 'AUT_Fluency_Diff'});

resultsPsilo= table(matchedTable.ParticipantID_Baseline, ...
    Psilo.Dose, Psilo.Session,...
    Psilo.RAT_Accuracy - matchedTable.RAT_Accuracy_Baseline, ...
    Psilo.RAT_Accurate_Insight - matchedTable.RAT_Accurate_Insight_Baseline, ...
    Psilo.RAT_Inaccurate_Insight - matchedTable.RAT_Inaccurate_Insight_Baseline, ...
    Psilo.RAT_N_A_Insight - matchedTable.RAT_N_A_Insight_Baseline, ...
    Psilo.AUT_Originality - matchedTable.AUT_Originality_Baseline, ...
    Psilo.AUT_Fluency - matchedTable.AUT_Fluency_Baseline, ...
    'VariableNames', {'ParticipantID', 'Dose', 'Session', 'RAT_Accuracy_Diff', 'RAT_Accurate_Insight_Diff', ...
                      'RAT_Inaccurate_Insight_Diff', 'RAT_N_A_Insight_Diff', ...
                      'AUT_Originality_Diff', 'AUT_Fluency_Diff'});

CombinedResults = [resultsPlacebo; resultsPsilo]

% Replace values only in specific columns, e.g., columns 2 to 4
CombinedResults{:, 4:end}(CombinedResults{:, 4:end} > 900) = 999;

writetable(CombinedResults, '/Users/zsayali1/Documents/2104_Creativity/AUTRATDiff.csv', 'Delimiter', ',');
